# Generated by Django 2.2.5 on 2019-09-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('nickname', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
    ]
